### ISSUE TITLE
Remaining maintenance work

### ISSUE THREAD

**Issue by Windvis** [lblod/frontend-public-decisions#16]
Required before split:
- [x] Modernize the CurrentSession service (or remove it if it's not used) (#19)
- [x] "Reset filters" no longer clears the form fields (#18)
- [x] ember-simple-auth tweaks, it seems the previous upgrade wasn't implemented 100% correctly
- [x] add a favicon (#17)
- [x] search page FAQ seems outdated? ("Hoe moet ik de filters gebruiken" lists a filter that isn't part of the app) (#20)
- [x] retrieve the app name from the environment config to make it easier to change (#22)
- [x] make the footer reusable instead of copy pasting it to multiple pages (#21)
- [x] use AuLink and AuLinkExternal where needed for the proper link styling 

Nice to haves:

- [ ] ~~Ember 4.4 LTS update~~ not possible yet.
  - torii (we can work around this by using the [adopted ember addons fork](https://github.com/adopted-ember-addons/torii)
  - ember-submission-form-fields triggers errors similar to this:
    > Uncaught Error: Assertion Failed: You attempted to update `nodeValue` on `RdfInputFieldsDateTimeComponent`, but it had already been used previously in the same computation.  Attempting to update a value after using it in a computation can cause logical errors, infinite revalidation bugs, and performance issues, and is not supported.
- [ ] ~~Embroider~~ It seems this isn't recommended until Ember Data is converted to a v2 addon
- [ ] Model cleanup
  - it seems not all model classes are used (or needed)
  - all relationships need explicit inverses
  - custom inflector rules
